"""
Seed CustodyChain with synthetic exhibits for the demo.

Everything here is invented. No real people, no real cases, no real files:
the "exhibits" are generated bytes that stand in for a notice, a chat export,
a small image, and a log file. The hash chain does not care what the bytes
represent, so synthetic content demonstrates the product exactly as well as
real content would — without putting anyone's data in a demo database.

Usage:
    cd backend
    python seed_demo.py
"""
from __future__ import annotations

import struct
import sys
import zlib
from datetime import datetime, timedelta, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from app import custody  # noqa: E402
from app.custody import EXHIBIT_STORE  # noqa: E402
from app.database import get_conn, init_db  # noqa: E402


def _iso(base: datetime, **delta) -> str:
    return (base + timedelta(**delta)).isoformat()


# --------------------------------------------------------------------------
# Synthetic exhibit content
# --------------------------------------------------------------------------

def make_notice_pdf() -> bytes:
    """A tiny but genuinely valid PDF, built by hand so the seed needs no
    PDF library and the file really opens."""
    text = (
        "BT /F1 13 Tf 60 720 Td (PUBLIC NOTICE - SYNTHETIC DEMO FILE) Tj "
        "0 -26 Td (Ward 6 water supply works) Tj "
        "0 -20 Td (Notice period: 14 days from posting.) Tj "
        "0 -20 Td (This document is invented for a demonstration.) Tj ET"
    )
    objs = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
        b"/Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",
        b"<< /Length " + str(len(text)).encode() + b" >>\nstream\n"
        + text.encode() + b"\nendstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]
    out = bytearray(b"%PDF-1.4\n")
    offsets = []
    for i, body in enumerate(objs, start=1):
        offsets.append(len(out))
        out += f"{i} 0 obj\n".encode() + body + b"\nendobj\n"
    xref_at = len(out)
    out += f"xref\n0 {len(objs) + 1}\n".encode()
    out += b"0000000000 65535 f \n"
    for off in offsets:
        out += f"{off:010d} 00000 n \n".encode()
    out += (f"trailer\n<< /Size {len(objs) + 1} /Root 1 0 R >>\n"
            f"startxref\n{xref_at}\n%%EOF\n").encode()
    return bytes(out)


def make_chat_export() -> bytes:
    lines = [
        "CHAT EXPORT (SYNTHETIC - NOT REAL PEOPLE)",
        "Group: Ward 6 residents",
        "",
        "[2026-01-04 18:02] Resident A: The water has been off since Friday.",
        "[2026-01-04 18:05] Resident B: Same on our street. Any notice posted?",
        "[2026-01-04 18:09] Resident A: There is a notice on the board now.",
        "[2026-01-04 18:11] Resident C: I took a photo of it, sending now.",
        "[2026-01-04 18:14] Resident B: That says fourteen days.",
        "[2026-01-04 18:20] Resident A: We should keep a copy of the original.",
        "",
        "-- end of export --",
    ]
    return ("\n".join(lines) + "\n").encode("utf-8")


def make_png(width: int = 96, height: int = 96) -> bytes:
    """A small valid PNG with a simple pattern, written by hand (zlib only)."""
    raw = bytearray()
    for y in range(height):
        raw.append(0)  # filter: none
        for x in range(width):
            r = (x * 255) // max(1, width - 1)
            g = (y * 255) // max(1, height - 1)
            b = 120 if ((x // 12) + (y // 12)) % 2 == 0 else 60
            raw += bytes((r, g, b))

    def chunk(tag: bytes, data: bytes) -> bytes:
        return (struct.pack(">I", len(data)) + tag + data
                + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF))

    header = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    return (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", header)
            + chunk(b"IDAT", zlib.compress(bytes(raw), 9)) + chunk(b"IEND", b""))


def make_log_file() -> bytes:
    base = datetime(2026, 1, 4, 17, 0, tzinfo=timezone.utc)
    lines = ["# SYNTHETIC device log - generated for a demonstration"]
    for i in range(60):
        t = (base + timedelta(seconds=i * 37)).strftime("%Y-%m-%dT%H:%M:%SZ")
        level = "INFO" if i % 7 else "WARN"
        lines.append(f"{t} {level} pump.station6 pressure={2.4 + (i % 9) * 0.05:.2f}bar")
    return ("\n".join(lines) + "\n").encode("utf-8")


# --------------------------------------------------------------------------
# Cases
# --------------------------------------------------------------------------

BASE_TIME = datetime(2026, 1, 5, 9, 0, tzinfo=timezone.utc)

CASES = [
    {
        "case_id": "CASE-2026-014",
        "exhibits": [
            {
                "filename": "ward6_public_notice.pdf",
                "content": make_notice_pdf,
                "description": "Public notice photographed on the ward noticeboard",
                "collected_by": "A. Bello",
                "collected_role": "Collecting officer",
                "collected_place": "Ward 6 noticeboard, Ikeja",
                "events": [
                    ("TRANSFERRED", "A. Bello", "Collecting officer",
                     {"from_person": "A. Bello", "to_person": "C. Okafor"}, 150),
                    ("RECEIVED", "C. Okafor", "Analyst",
                     {"from_person": "A. Bello", "to_person": "C. Okafor"}, 165),
                    ("ANALYSED", "C. Okafor", "Analyst",
                     {"note": "Compared against the council's published notice register."}, 300),
                ],
            },
            {
                "filename": "residents_chat_export.txt",
                "content": make_chat_export,
                "description": "Resident group chat export covering the notice period",
                "collected_by": "A. Bello",
                "collected_role": "Collecting officer",
                "collected_place": "Handset handed in at the ward office",
                "events": [
                    ("COPIED", "A. Bello", "Collecting officer",
                     {"note": "Working copy made for the case file."}, 40),
                    ("VIEWED", "D. Adeyemi", "Counsel", {}, 400),
                ],
            },
        ],
    },
    {
        "case_id": "CASE-2026-021",
        "exhibits": [
            {
                "filename": "noticeboard_photo.png",
                "content": make_png,
                "description": "Photograph of the noticeboard as found",
                "collected_by": "C. Okafor",
                "collected_role": "Analyst",
                "collected_place": "Ward 6 noticeboard, Ikeja",
                "events": [
                    ("VIEWED", "D. Adeyemi", "Counsel", {}, 220),
                    ("EXPORTED", "D. Adeyemi", "Counsel",
                     {"note": "Exported for the bundle served on the other side."}, 260),
                ],
            },
        ],
    },
    {
        "case_id": "CASE-2026-033",
        "exhibits": [
            {
                "filename": "pump_station_6.log",
                "content": make_log_file,
                "description": "Device log pulled from the pump station controller",
                "collected_by": "M. Idris",
                "collected_role": "Analyst",
                "collected_place": "Pump station 6, plant room",
                "events": [
                    ("TRANSFERRED", "M. Idris", "Analyst",
                     {"from_person": "M. Idris", "to_person": "Evidence store"}, 90),
                    ("RETURNED", "Evidence store", "Other",
                     {"note": "Returned to the analyst for a second reading."}, 500),
                ],
            },
        ],
    },
]


def seed() -> None:
    init_db()
    EXHIBIT_STORE.mkdir(exist_ok=True)

    created = []
    with get_conn() as conn:
        custody.init_custody_schema(conn)

        # Start from a clean demo set so reruns don't pile up duplicates.
        conn.execute("DELETE FROM custody_events")
        conn.execute("DELETE FROM checks")
        conn.execute("DELETE FROM exhibits")

        minute = 0
        for case in CASES:
            for spec in case["exhibits"]:
                content = spec["content"]()
                exhibit_id = custody.generate_exhibit_id(conn)
                dest = EXHIBIT_STORE / f"{exhibit_id}__{spec['filename']}"
                dest.write_bytes(content)

                sha256 = custody.sha256_file(dest)
                collected_at = _iso(BASE_TIME, minutes=minute)
                minute += 45

                conn.execute(
                    """INSERT INTO exhibits
                       (exhibit_id, case_id, description, collected_by, collected_role,
                        collected_place, collected_at, original_filename, filesize,
                        sha256, storage_path, created_at)
                       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                    (
                        exhibit_id, case["case_id"], spec["description"],
                        spec["collected_by"], spec["collected_role"],
                        spec["collected_place"], collected_at, spec["filename"],
                        len(content), sha256, str(dest), custody.now_iso(),
                    ),
                )

                custody.append_event(
                    conn, exhibit_id=exhibit_id, actor_name=spec["collected_by"],
                    actor_role=spec["collected_role"], action="COLLECTED",
                    note=spec["description"], occurred_at=collected_at,
                )
                for action, actor, role, extra, offset in spec["events"]:
                    custody.append_event(
                        conn, exhibit_id=exhibit_id, actor_name=actor, actor_role=role,
                        action=action,
                        from_person=extra.get("from_person"),
                        to_person=extra.get("to_person"),
                        note=extra.get("note"),
                        occurred_at=_iso(BASE_TIME, minutes=minute - 45 + offset),
                    )

                created.append((exhibit_id, case["case_id"], spec["filename"], sha256))

        # Confirm every seeded chain verifies before we claim success.
        for exhibit_id, *_ in created:
            status = custody.verify_chain(custody.load_events(conn, exhibit_id))
            if not status.ok:
                raise SystemExit(f"Seeded chain for {exhibit_id} is broken: {status.reason}")

    print(f"Seeded {len(created)} synthetic exhibits across {len(CASES)} cases.\n")
    for exhibit_id, case_id, filename, sha256 in created:
        print(f"  {exhibit_id}  {case_id:<16} {filename:<30} seal {sha256[:16]}…")
    print("\nAll custody chains verified intact.")
    print("Start the API with:  uvicorn app.main:app --reload --port 8000")
    print("Then open public/exhibits.html and pick any exhibit to run the tamper demo.")


if __name__ == "__main__":
    seed()
