"""
CustodyChain — report_pdf.py  (ADDITIVE MODULE)

Builds the downloadable verification report described in Part 4 of the
public verify flow brief. Takes a plain dict of already computed values
(hashes, similarity score, explanation) and lays them out as a PDF. It
does not recompute or re verify anything — the caller is responsible for
producing correct inputs from the existing verify endpoint and the new
analysis endpoint.
"""
from __future__ import annotations

import io
from datetime import datetime, timezone

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

VERDICT_COLORS = {
    "verified": colors.HexColor("#0C7A43"),
    "caution": colors.HexColor("#B5560A"),
    "altered": colors.HexColor("#B3261E"),
}


def build_report_pdf(data: dict) -> bytes:
    """data keys: file_name, file_type, verified_at (iso string), original_hash,
    compare_hash, similarity_pct, verdict_tier ('verified'|'caution'|'altered'),
    verdict_label, explanation, extra_notes (optional list[str])."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=LETTER, topMargin=0.85 * inch, bottomMargin=0.85 * inch,
                             leftMargin=0.85 * inch, rightMargin=0.85 * inch)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("ReportTitle", parent=styles["Title"], fontSize=20, spaceAfter=4, textColor=colors.HexColor("#101828"))
    subtitle_style = ParagraphStyle("ReportSubtitle", parent=styles["Normal"], fontSize=10.5, textColor=colors.HexColor("#475467"), spaceAfter=18)
    section_style = ParagraphStyle("Section", parent=styles["Heading2"], fontSize=13, spaceBefore=14, spaceAfter=6, textColor=colors.HexColor("#101828"))
    body_style = ParagraphStyle("Body", parent=styles["Normal"], fontSize=10.5, leading=15, textColor=colors.HexColor("#344054"))
    mono_style = ParagraphStyle("Mono", parent=styles["Normal"], fontName="Courier", fontSize=8.5, leading=12, textColor=colors.HexColor("#475467"))

    verdict_color = VERDICT_COLORS.get(data.get("verdict_tier", "caution"), colors.HexColor("#B5560A"))
    verdict_style = ParagraphStyle("Verdict", parent=styles["Heading1"], fontSize=16, textColor=verdict_color, spaceAfter=10)

    elements = []
    elements.append(Paragraph("File verification report", title_style))
    elements.append(Paragraph("Generated by CustodyChain, a media and civic trust verification tool.", subtitle_style))

    elements.append(Paragraph(data.get("verdict_label", ""), verdict_style))
    elements.append(Paragraph(data.get("explanation", ""), body_style))

    elements.append(Paragraph("Summary", section_style))
    summary_rows = [
        ["File name", data.get("file_name", "")],
        ["File type", data.get("file_type", "")],
        ["Verified at", _format_time(data.get("verified_at", ""))],
        ["Similarity score", f"{data.get('similarity_pct', 0)} percent"],
    ]
    summary_table = Table(summary_rows, colWidths=[1.7 * inch, 4.3 * inch])
    summary_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#667085")),
        ("TEXTCOLOR", (1, 0), (1, -1), colors.HexColor("#101828")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("LINEBELOW", (0, 0), (-1, -2), 0.5, colors.HexColor("#E4E7EC")),
    ]))
    elements.append(summary_table)

    elements.append(Paragraph("Cryptographic fingerprints (SHA 256)", section_style))
    elements.append(Paragraph("Original file", ParagraphStyle("Label", parent=body_style, fontSize=9, textColor=colors.HexColor("#667085"))))
    elements.append(Paragraph(data.get("original_hash", ""), mono_style))
    elements.append(Spacer(1, 6))
    elements.append(Paragraph("Compared file", ParagraphStyle("Label2", parent=body_style, fontSize=9, textColor=colors.HexColor("#667085"))))
    elements.append(Paragraph(data.get("compare_hash", ""), mono_style))

    extra_notes = data.get("extra_notes") or []
    if extra_notes:
        elements.append(Paragraph("Additional detail", section_style))
        for note in extra_notes:
            elements.append(Paragraph("• " + note, body_style))
            elements.append(Spacer(1, 3))

    elements.append(Spacer(1, 20))
    elements.append(Paragraph(
        "This report reflects an automated comparison of two files using cryptographic "
        "hashing and supporting analysis, generated at the time shown above. It may be "
        "kept as a record of this verification for evidentiary or archival purposes. It "
        "does not by itself establish the origin or authenticity of either file.",
        ParagraphStyle("Disclaimer", parent=body_style, fontSize=9, textColor=colors.HexColor("#667085"), leading=13),
    ))

    doc.build(elements)
    return buf.getvalue()


def _format_time(iso_string: str) -> str:
    try:
        dt = datetime.fromisoformat(iso_string.replace("Z", "+00:00"))
        return dt.astimezone(timezone.utc).strftime("%d %b %Y, %H:%M UTC")
    except (ValueError, AttributeError):
        return iso_string or datetime.now(timezone.utc).strftime("%d %b %Y, %H:%M UTC")


# ==========================================================================
# Court report for a sealed exhibit  (ADDITIVE — the existing
# build_report_pdf above is untouched and still serves the ad-hoc compare)
#
# Audience: a magistrate with no technical background. Rules followed here:
#   - short words, no lecture on cryptography
#   - the SHA-256 hex is labelled "Seal number", with the algorithm in small print
#   - "Unchanged / Changed", not "hash match"
#   - the honest limit is printed on every report, not buried
# ==========================================================================

CHAIN_COLORS = {
    True: colors.HexColor("#0C7A43"),   # --verified-dark
    False: colors.HexColor("#B3261E"),  # --altered-dark
}

_ACTION_WORDS = {
    "COLLECTED": "Collected",
    "COPIED": "Made a copy",
    "TRANSFERRED": "Handed over",
    "RECEIVED": "Received",
    "VIEWED": "Viewed",
    "ANALYSED": "Examined",
    "EXPORTED": "Exported",
    "RETURNED": "Returned",
    "SEAL_CHECKED": "Checked the seal",
    "NOTE": "Note",
}


def _plain_action(action: str) -> str:
    return _ACTION_WORDS.get((action or "").upper(), (action or "").title())


def _short_time(iso_string: str) -> str:
    try:
        dt = datetime.fromisoformat(str(iso_string).replace("Z", "+00:00"))
        return dt.astimezone(timezone.utc).strftime("%d %b %Y, %H:%M UTC")
    except (ValueError, AttributeError, TypeError):
        return str(iso_string or "")


def build_court_report_pdf(exhibit: dict, events: list, chain_ok: bool,
                            chain_reason, latest_check, limit_sentence: str) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=LETTER, topMargin=0.8 * inch,
                            bottomMargin=0.8 * inch, leftMargin=0.8 * inch,
                            rightMargin=0.8 * inch)
    styles = getSampleStyleSheet()
    ink = colors.HexColor("#101828")
    body_col = colors.HexColor("#344054")
    muted = colors.HexColor("#667085")
    border = colors.HexColor("#E4E7EC")

    title_style = ParagraphStyle("CourtTitle", parent=styles["Title"], fontSize=19,
                                 spaceAfter=2, textColor=ink)
    subtitle_style = ParagraphStyle("CourtSub", parent=styles["Normal"], fontSize=10,
                                    textColor=muted, spaceAfter=16)
    section_style = ParagraphStyle("CourtSection", parent=styles["Heading2"], fontSize=12.5,
                                   spaceBefore=15, spaceAfter=6, textColor=ink)
    body_style = ParagraphStyle("CourtBody", parent=styles["Normal"], fontSize=10.5,
                                leading=15, textColor=body_col)
    small_style = ParagraphStyle("CourtSmall", parent=styles["Normal"], fontSize=8.5,
                                 leading=12, textColor=muted)
    seal_style = ParagraphStyle("Seal", parent=styles["Normal"], fontName="Courier",
                                fontSize=9.5, leading=13, textColor=ink)
    cell_style = ParagraphStyle("Cell", parent=styles["Normal"], fontSize=9,
                                leading=12, textColor=body_col)

    el = []
    el.append(Paragraph("Chain of custody report", title_style))
    el.append(Paragraph(
        f"Case {exhibit.get('case_id', '')} &nbsp;·&nbsp; Exhibit {exhibit.get('exhibit_id', '')}",
        subtitle_style))

    # ---- Headline status: the two things a magistrate actually needs ----
    if latest_check:
        check_word = "Unchanged" if latest_check.get("match") else "Changed"
    else:
        check_word = "Not yet checked"
    chain_word = "Intact" if chain_ok else "Broken"

    status_rows = [[
        Paragraph("<b>Custody record</b><br/>" + chain_word,
                  ParagraphStyle("S1", parent=body_style,
                                 textColor=CHAIN_COLORS[bool(chain_ok)], fontSize=11)),
        Paragraph("<b>Latest check of the file</b><br/>" + check_word,
                  ParagraphStyle("S2", parent=body_style, fontSize=11,
                                 textColor=(CHAIN_COLORS[True] if latest_check
                                            and latest_check.get("match")
                                            else CHAIN_COLORS[False] if latest_check
                                            else muted))),
    ]]
    status_table = Table(status_rows, colWidths=[3.35 * inch, 3.35 * inch])
    status_table.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 0.6, border),
        ("INNERGRID", (0, 0), (-1, -1), 0.6, border),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING", (0, 0), (-1, -1), 12),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    el.append(status_table)

    # ---- Plain English summary ----
    el.append(Paragraph("In plain words", section_style))
    el.append(Paragraph(_summary_paragraph(exhibit, events, chain_ok, chain_reason,
                                           latest_check), body_style))

    # ---- The exhibit ----
    el.append(Paragraph("The exhibit", section_style))
    info_rows = [
        ["File name", exhibit.get("original_filename", "")],
        ["File size", _human_size(exhibit.get("filesize", 0))],
        ["Collected by", f"{exhibit.get('collected_by', '')} ({exhibit.get('collected_role', '')})"],
        ["Place collected", exhibit.get("collected_place") or "Not recorded"],
        ["Time collected", _short_time(exhibit.get("collected_at", ""))],
        ["Description", exhibit.get("description") or "Not recorded"],
    ]
    info_table = Table([[Paragraph(k, ParagraphStyle("K", parent=cell_style, textColor=muted)),
                         Paragraph(str(v), cell_style)] for k, v in info_rows],
                       colWidths=[1.6 * inch, 5.1 * inch])
    info_table.setStyle(TableStyle([
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LINEBELOW", (0, 0), (-1, -2), 0.5, border),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    el.append(info_table)

    # ---- Seal number ----
    el.append(Paragraph("Seal number", section_style))
    el.append(Paragraph(
        "This is the unique seal taken from the file at the moment it was collected. "
        "If even one character of the file changes, this seal changes completely.",
        body_style))
    el.append(Spacer(1, 6))
    el.append(Paragraph(_wrap_hex(exhibit.get("sha256", "")), seal_style))
    el.append(Spacer(1, 4))
    el.append(Paragraph("Seal produced using SHA-256.", small_style))

    # ---- Custody trail ----
    el.append(Paragraph("Who held the exhibit, and what they did", section_style))
    header = ["When", "Who", "Role", "What they did", "From / to"]
    table_data = [[Paragraph(f"<b>{h}</b>", ParagraphStyle("H", parent=cell_style,
                                                           textColor=muted)) for h in header]]
    for ev in events:
        movement = ""
        if ev.get("from_person") or ev.get("to_person"):
            movement = f"{ev.get('from_person') or '—'} → {ev.get('to_person') or '—'}"
        table_data.append([
            Paragraph(_short_time(ev.get("occurred_at", "")), cell_style),
            Paragraph(str(ev.get("actor_name", "")), cell_style),
            Paragraph(str(ev.get("actor_role", "")), cell_style),
            Paragraph(_plain_action(ev.get("action", "")), cell_style),
            Paragraph(movement or "—", cell_style),
        ])
    trail = Table(table_data, colWidths=[1.45 * inch, 1.35 * inch, 1.1 * inch,
                                         1.4 * inch, 1.4 * inch], repeatRows=1)
    trail.setStyle(TableStyle([
        ("LINEBELOW", (0, 0), (-1, 0), 0.8, border),
        ("LINEBELOW", (0, 1), (-1, -2), 0.4, border),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    el.append(trail)

    if not chain_ok and chain_reason:
        el.append(Spacer(1, 8))
        el.append(Paragraph(
            "<b>Warning about this custody record:</b> " + str(chain_reason),
            ParagraphStyle("Warn", parent=body_style, textColor=CHAIN_COLORS[False])))

    # ---- Latest check detail ----
    if latest_check:
        el.append(Paragraph("The latest check", section_style))
        el.append(Paragraph(str(latest_check.get("summary", "")), body_style))
        el.append(Spacer(1, 6))
        el.append(Paragraph("Seal taken from the copy that was checked:", small_style))
        el.append(Paragraph(_wrap_hex(latest_check.get("copy_sha256", "")), seal_style))
        el.append(Spacer(1, 4))
        el.append(Paragraph(
            f"Checked on {_short_time(latest_check.get('created_at', ''))}, "
            f"file name: {latest_check.get('copy_filename', '')}.", small_style))

    # ---- Honest limit ----
    el.append(Paragraph("What this report does not prove", section_style))
    el.append(Paragraph(limit_sentence, body_style))

    el.append(Spacer(1, 18))
    el.append(Paragraph(
        "Generated by CustodyChain at "
        + datetime.now(timezone.utc).strftime("%d %b %Y, %H:%M UTC") + ".",
        small_style))

    doc.build(el)
    return buf.getvalue()


def _summary_paragraph(exhibit, events, chain_ok, chain_reason, latest_check) -> str:
    name = exhibit.get("original_filename", "This file")
    who = exhibit.get("collected_by", "an officer")
    when = _short_time(exhibit.get("collected_at", ""))
    place = exhibit.get("collected_place")
    where = f" at {place}" if place else ""

    parts = [
        f"<b>{name}</b> was collected by {who}{where} on {when}. "
        f"At that moment the file was sealed, and {len(events)} "
        f"{'entry has' if len(events) == 1 else 'entries have'} been recorded "
        "in its custody trail since."
    ]
    if chain_ok:
        parts.append(
            "The custody trail is intact: no entry has been added, removed, or "
            "edited after it was written."
        )
    else:
        parts.append(
            "<b>The custody trail is broken.</b> " + (str(chain_reason) or "")
        )
    if latest_check is None:
        parts.append(
            "No copy of this file has been checked against the seal yet."
        )
    elif latest_check.get("match"):
        parts.append(
            "The most recent copy checked against the seal was <b>unchanged</b>: "
            "it is identical to the file that was collected."
        )
    else:
        parts.append(
            "The most recent copy checked against the seal was <b>changed</b>: "
            "it is not the same file that was collected."
        )
    return " ".join(parts)


def _wrap_hex(value: str, group: int = 16) -> str:
    value = str(value or "")
    return " ".join(value[i:i + group] for i in range(0, len(value), group))


def _human_size(n) -> str:
    try:
        n = int(n)
    except (TypeError, ValueError):
        return str(n)
    if n < 1024:
        return f"{n} bytes"
    if n < 1024 * 1024:
        return f"{n / 1024:.0f} KB"
    return f"{n / (1024 * 1024):.1f} MB"
